### ISSUE TITLE
Input jsonl file required for inference_sthv2.py

### ISSUE THREAD

**Issue by sroutray** [LatentActionPretraining/LAPA#13]
Hi, I am trying to get latent actions using the LAQ model on the OpenX dataset. How could we get the jsonl file required as `--input_file` in the script provided inference_sthv2.py? OpenX follows RLDS data format, how to convert that to the jsonl file format required by inference_sthv2.py?

**Comment by sroutray** [comment]
Also, is there a specific subset of OpenX that you are using for pretraining? Please let us know.

**Comment by seonghyeonye** [comment]
Hi, we precomputed the instruction and vision value and saved them into a jsonl file. Since our vision encoder is a vqgan encoder, the image representation can be saved as discrete tokens. Therefore, the `--input_file` has the following format:

```json
{"instruction": "<s> You are a helpful assistant. USER: What action should the robot take to `put eggplant into yellow basket` ASSISTANT:", "vision": ["754", "1512", ...], "fields": "[instruction],[vision],delta"}
```

The `delta` value is obtained from the inference_sthv2.py file.
