### ISSUE TITLE
Presence of explicit bin edges in `finetune_preprocess.py`

### ISSUE THREAD

**Issue by kausiksivakumar** [LatentActionPretraining/LAPA#5]
Hey, thanks for sharing an amazing work. I was curious about the explicit addition of 
`total_bin[-1] = [-0.5,0.5,1.5]` in line 69 of finetune preprocess? This seems to be a delibrate addition, could you shed some light into why? and what siginificance do these numbers have? Thanks

**Comment by seonghyeonye** [comment]
This part is just for implementation convenience. Since we go through get_average_values function (https://github.com/LatentActionPretraining/LAPA/blob/main/latent_pretraining/deploy.py#L125C9-L125C28) for each row, the gripper value would be 0 (average of -0.5 and 0.5) or 1 (average of 0.5 and 1.5). This is just for implementation convenience and you can change into other values like [-0.1, 0.1, 1.9].
